# Generated by Django 4.2.2 on 2023-06-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('log_file', models.CharField(max_length=255)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
