# Generated by Django 4.2.2 on 2023-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdRun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandexecution',
            old_name='executed_at',
            new_name='start_execution',
        ),
        migrations.AddField(
            model_name='commandexecution',
            name='end_execution',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
